name: Build Funcora (Windows)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install --upgrade nuitka
          pip install -r requirements.txt

      - name: Build Funcora
        run: |
          python -m nuitka ^
            --standalone ^
            --onefile ^
            --lto=yes ^
            --windows-console-mode=disable ^
            --enable-plugin=pyside6 ^
            --include-data-dir=assets=assets ^
            --output-dir=build ^
            --output-filename=Funcora.exe ^
            Funcora.py

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: Funcora-Windows
          path: build/Funcora.exe

